### ISSUE TITLE
Initial Feedback for Introduction

### ISSUE THREAD

**Issue by mankyKitty** [qfpl/reflex-tutorial#1]
- The line starting with "The original definition...", is that meant to be a bullet point list?

-  Think that first "and" should be "the" in up a data structure that describes and FRP network and how 

 - Possible rewording required for "The alternative is to pull out the state you are interested in from all through the tree, and to put it back in to the same places when you are rendering the DOM". I can kind of see what you're getting at but it doesn't read very well.

- "we periodically here from people", wrong 'hear' :)

- At the end of the post where you're mentioning how to install Reflex. I think it would be good to direct people to the README and other related docs on the reflex-platform as the source of truth for install instructions. It may be generally implied, but can't hurt.

**Comment by dalaing** [comment]
Addressed (although you might need to do a hard reload to pick up on it).  Thanks!
