### ISSUE TITLE
Fizz Buzz examples don't work on Android phone

### ISSUE THREAD

**Issue by vertexcite** [qfpl/reflex-tutorial#8]
The Fizz Buzz examples don't work on my Android Phone (tried on Firefox and Chrome).  Integer input pops up numeric keypad, but derived outputs don't respond to any edits of input.

Excellent tutorial so far, by the way :-)

**Comment by dalaing** [comment]
Thanks for letting me know.

I've put up a change where I just use a button for that counter rather than a number input, and tested it in an icongnito window.  I'm having a hard time triggering a hard refresh to test it out in a regular window, but at least it will work for new users.

**Comment by vertexcite** [comment]
LGTM
